### PR TITLE
Jupyterlab4 port of the extension

### PR DESCRIPTION
**Pull request by mwouts**
Will close https://github.com/mwouts/jupytext/issues/1054

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @mwouts for working on this!

While investigating Jupytext support in Notebook 7 (https://github.com/jupyter/notebook/issues/6914) it appears that the toolbar is missing when opening a markdown file with the `Jupytext Notebook` factory (but not with the `Notebook` factory), in both JupyterLab and Notebook 7: https://github.com/jupyter/notebook/pull/6923#issuecomment-1593545798

https://github.com/jupyter/notebook/assets/591645/293f0bae-59a6-4e96-ae1a-2cf144f73791

**Comment by mwouts** [comment]
Hey @jtpio , thank you for pointing this out! Well I am a bit clueless but I will pay attention to this, that is a strange pattern indeed.

By the way I plan to work on this issue this week-end. I think I would have a preference to continue packaging everything (I mean the Python package, the CLI, the contents manager, the server and the jupyter lab extension) in `jupytext`, because it makes it simpler to install - but I need to see if I can get this to work.

**Comment by jtpio** [comment]
> packaging everything (I mean the Python package, the CLI, the contents manager, the server and the jupyter lab extension) in `jupytext`, because it makes it simpler to install

Right that makes sense :+1:

**Comment by parmentelat** [comment]
>  I would have a preference to continue packaging everything (I mean the Python package, the CLI, the contents manager, the server and the jupyter lab extension) in jupytext

there currently are 2 different codebases for jlab3 and jlab4, and in this respect (as well as in other areas maybe) it could become a challenge

for this reason I have asked discourse to see if the community has best practices on how to deal with that
https://discourse.jupyter.org/t/jlab-extensions-that-target-both-jlab3-and-jlab4/

with these answers I can maybe propose to tweak the code of this extension to make it work with both jlab3 and jlab4, if that's helpful

**Comment by parmentelat** [comment]
for the record, the issue mentioned above by @jtpio - missing toolbar in the juptext notebook widget - is also the topic of mwouts/jupytext#1107 and fixed in mwouts/jupytext#1109

**Comment by mwouts** [comment]
Closing this PR as I am going to archive this repository (for the second time :smile:)

We will continue to provide the extension in Jupytext. Starting from `jupytext==1.15.0`, thanks to @parmentelat , the extension will be compatible with both JupyterLab 3 and JupyterLab 4.

**Pull request closed without merging**
